
GET http://localhost:3000/api/persons
###
GET http://localhost:3000/api/persons/5e9326a9368c5446b7899e08
###
GET http://localhost:3000/api/persons/5e948f60f56f9230cb955759
####
GET http://localhost:3000/api/persons/5e948f60f56f923043534
####
DELETE http://localhost:3000/api/persons/5
###
POST http://localhost:3000/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Tuure",
  "number": "+358 50 4646468"
}
###
POST http://localhost:3000/api/persons HTTP/1.1
Content-Type: application/json

{
  "number": "1"
}
###
POST http://localhost:3000/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "zz",
  "number": "123324324"
}
